[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
  " 自動削除有効化
  let g:dein#auto_recache = 1
'''

# -----------------------------------------------------------------------
# ファイラ/ターミナル
# -----------------------------------------------------------------------

[[plugins]] # ファイラ
repo = 'lambdalisue/fern.vim'
hook_add = '''
" 起動
nnoremap <silent><C-w> :Fern . -drawer -reveal=% -toggle -stay<CR>

" Boxフォルダを開く
nnoremap <silent><Leader>m :Fern $HOME/Library/CloudStorage/Box-Box/ -drawer -toggle -stay<CR>

" 隠しファイルを表示する
let g:fern#default_hidden=1

'''

[[plugins]] # fernの動作改善
repo = 'antoinemadec/FixCursorHold.nvim'

[[plugins]] # fernでプレビューする
repo = 'yuki-yano/fern-preview.vim'
hook_add = '''
function! s:fern_settings() abort
  nmap <silent> <buffer> p     <Plug>(fern-action-preview:toggle)
  nmap <silent> <buffer> <C-p> <Plug>(fern-action-preview:auto:toggle)
  nmap <silent> <buffer> <C-d> <Plug>(fern-action-preview:scroll:down:half)
  nmap <silent> <buffer> <C-u> <Plug>(fern-action-preview:scroll:up:half)
endfunction

augroup fern-settings
  autocmd!
  autocmd FileType fern call s:fern_settings()
augroup END
'''

[[plugins]] # telescopeの依存プラグイン
repo = "nvim-lua/plenary.nvim"

[[plugins]] # fuzzy finder
repo = "nvim-telescope/telescope.nvim"
hook_add = '''
nnoremap <leader>g <cmd>lua require('telescope.builtin').live_grep({grep_open_files=true})<CR>
'''

[[plugins]] # インタプリタ実行
repo = 'thinca/vim-quickrun'
hook_add = '''
nnoremap <Leader>r :QuickRun -mode n<CR>
vnoremap <Leader>r :QuickRun -mode v<CR>

" 実行時のウィンドウの開き方を指定する
let g:quickrun_config = {
    \ '_': {
        \ 'outputter': 'error',
        \ 'outputter/error/success': 'quickfix',
        \ 'outputter/error/error'  : 'quickfix',
        \ 'outputter/buffer/split' : ':botright 8sp',
        \ 'outputter/buffer/close_on_empty': 1,
      \ }
    \ }
'''

# -----------------------------------------------------------------------
# 表示
# -----------------------------------------------------------------------

[[plugins]] # カラースキーマ
repo = 'jonathanfilip/vim-lucius'

[[plugins]] # インデントに線を表示する
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_color_term =239
let g:indentLine_color_gui = '#708090'
let g:indentLine_char = '¦'
'''

[[plugins]] # ステータスバーを見やすくする
repo = 'vim-airline/vim-airline'
hook_add = '''
" 隣のバッファに移動する
nmap <C-n> <Plug>AirlineSelectNextTab
nmap <C-p> <Plug>AirlineSelectPrevTab

" ステータスラインの表示を変更する
let g:airline#extensions#default#layout = [
  \ [ 'a', 'b', 'c' ], ['x', 'y', 'z']
\ ]
let g:airline_section_b = '%{getcwd()}'    " カレントディレクトリを表示する
let g:airline_section_c = '%t %M'          " ファイル名だけ表示する
let g:airline_section_z = get(g:, 'airline_linecolumn_prefix', '').'%p%%'

" バッファタブの表示を変更する
let g:airline#extensions#tabline#enabled = 1        " タブライン機能を有効にする
let g:airline#extensions#tabline#fnamemod = ':t'    " ファイルパスを表示しない
let g:airline#extensions#tabline#show_buffers = 1   " バッファを表示する
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# -----------------------------------------------------------------------
# 補完
# -----------------------------------------------------------------------

[[plugins]] # Rubyのend等を自動入力する
repo = 'tpope/vim-endwise'

[[plugins]] # LSPを使う
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
build = '''
git checkout release
'''
hook_add = '''
" 対応言語追加
let g:coc_global_extensions = [
  \ 'coc-json', 'coc-css', 'coc-prettier','coc-jedi', 'coc-vimlsp', 'coc-sh', 'coc-git',
  \ 'coc-toml', 'coc-yaml', 'coc-solargraph', 'coc-pairs', 'coc-word', 'coc-html'
\ ]

" 候補を選択する
inoremap <silent><expr><C-n> coc#pum#visible() ? coc#pum#next(1) :CheckBackspace() ? "\<C-n>" :coc#refresh()
inoremap <expr><C-p> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"
" <CR>で候補を決定する
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm(): "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

function! CheckBackspace() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
'''

[[plugins]] # コメントアウトする
repo = 'tyru/caw.vim.git'
hook_add = '''
nmap cc <Plug>(caw:hatpos:toggle)
vmap cc <Plug>(caw:hatpos:toggle)
'''

[[plugins]] # 括弧で囲う
repo = 'tpope/vim-surround'

# -----------------------------------------------------------------------
# 移動
# -----------------------------------------------------------------------

[[plugins]] # 選択行を移動する
repo = 't9md/vim-textmanip'
hook_add = '''
vmap <C-j> <Plug>(textmanip-move-down)
vmap <C-k> <Plug>(textmanip-move-up)
vmap <C-h> <Plug>(textmanip-move-left)
vmap <C-l> <Plug>(textmanip-move-right)
'''

[[plugins]] # 行を跨いでf移動できるようにする
repo = 'rhysd/clever-f.vim'

[[plugins]] # easymotion系プラグイン
repo = 'yuki-yano/fuzzy-motion.vim'
hook_add = '''
nnoremap <Leader>f :FuzzyMotion<CR>
'''

[[plugins]] # fuzzy-motion依存プラグイン
repo = 'vim-denops/denops.vim'

# -----------------------------------------------------------------------
# 特定言語
# -----------------------------------------------------------------------

[[plugins]] # rails
repo = 'tpope/vim-rails'

[[plugins]] # markdown
repo = 'preservim/vim-markdown'
hook_add = '''
" 折りたたみを無効化する
let g:vim_markdown_folding_disabled = 1
" デフォルトのキーマップを無効化する
let g:vim_markdown_no_default_key_mappings = 1
" 改行時のインデント数を指定する
let g:vim_markdown_new_list_item_indent = 2
'''

[[plugins]] # pythonのインデントをPEP8準拠にする
repo = 'Vimjas/vim-python-pep8-indent'
